### ISSUE TITLE
Cursor not moving with lightspeed.nvim

### ISSUE THREAD

**Issue by tbenthompson** [vscode-neovim/vscode-neovim#1013]
I read through both:
- https://github.com/vscode-neovim/vscode-neovim/issues/804
- https://github.com/vscode-neovim/vscode-neovim/pull/868#issuecomment-1131963354

I also saw the updates that a recent update should mean that vscode-neovim should work out of the box with lightspeed. But, I'm not having success. 

With no other extensions enabled and an empty settings.json and init.vim:
<img width="578" alt="image" src="https://user-images.githubusercontent.com/4241811/185259193-34552871-0a9f-4cfb-a726-b3caf98b7d7f.png">

If I add the suggested `hi LightspeedCursor gui=reverse`, I get a double cursor where the VSCode cursor hasn't moved but there is a second cursor at the new location:

<img width="179" alt="image" src="https://user-images.githubusercontent.com/4241811/185259476-1cba804b-9679-4c9e-8036-531c5fa91d9c.png">

Thanks so much!

**Comment by theol0403** [comment]
The double cursor issue is a bug that cannot be fixed. It is due to the way that lightspeed doesn't actually move the cursor in certain situations.

https://github.com/ggandor/leap.nvim/issues/15#issuecomment-1168651304

The double cursor problem is minor, however. 

I'm not sure why you need the `hi LightspeedCursor gui=reverse` in the latest version, however. Check with empty settings.json.
