### ISSUE TITLE
Highlight color with leap.nvim in VS Code

### ISSUE THREAD

**Issue by Jendker** [vscode-neovim/vscode-neovim#1042]
It is not strictly an issue, just ask for help. If I use the excellent leap.nvim plugin the highlights are in bright green what makes them difficult to read, especially if font is light blue:
<img width="676" alt="Screenshot 2022-09-27 at 19 16 31" src="https://user-images.githubusercontent.com/14967831/192613275-8f976bc1-4af7-4289-b079-327d517f801c.png">
In nvim the highlights are red and there is no problem with readability. Do you know if there is a way to adjust the highlight color for this plugin in VSCode?

I'm sorry if this question has been answered already but I wasn't able to find the answer myself.

**Comment by theol0403** [comment]
This should have been fixed by https://github.com/vscode-neovim/vscode-neovim/pull/982.

Are you on the latest version of VSCode? 

If so, maybe you just need to specify the LeapMatch fg. Look at the leap documentation for specifying the match highlight group.

On my machine, I have the text fg to be black (as leap default), and it works properly in vscode.
