### ISSUE TITLE
set compositeEscape as jj or jk, cannot input J and K with capslock on

### ISSUE THREAD

**Issue by TheCrowd** [vscode-neovim/vscode-neovim#1111]
In windows, with Capslock on, and then typeq`j`, `j` will be input instead of `J`, and the same for `k`.  Turn off Capslock, can type J with `shift + j`

**Comment by justinmk** [comment]
insert mode or ...?

issue description is hard to understand.

**Comment by theol0403** [comment]
Yeah, this would be in insert mode. I think the issue is that caps j is triggering the vscode keybinding for j. This must be a vscode bug. Try keycode dispatch as shown in readme. Might be worth investigating in vscode.

Can only be solved using a different jk implementation. I think this is now possible by binding to type event with multithreaded ext host. 

Hopefully one day this will be done.
