### ISSUE TITLE
H/L/M keys can't be remapped

### ISSUE THREAD

**Issue by volny** [vscode-neovim/vscode-neovim#1135]
I want to remap shift-h and shift-l like this:
```
nnoremap H <Cmd>call VSCodeNotify('workbench.action.previousEditor')<CR>
nnoremap L <Cmd>call VSCodeNotify('workbench.action.nextEditor')<CR>
```

I saw in the [source](https://github.com/vscode-neovim/vscode-neovim/blob/master/package.json#L311-L346) that some keys bindings are hard-coded.

Is it possible to remap those keys?

Thanks!

**Comment by ctstacey** [comment]
Try this ... and let me know how you go :)
```vim
nnoremap <S-h> <Cmd>call VSCodeNotify('workbench.action.previousEditor')<CR>
nnoremap <S-l> <Cmd>call VSCodeNotify('workbench.action.nextEditor')<CR>
```

**Comment by ctstacey** [comment]
Those are commands that the extension makes available for use within VSCode.
However, on my system they are not mapped to any keys (i.e. not used).
Is it the same on your system?

![image](https://user-images.githubusercontent.com/51082452/217476632-cddb0b84-b259-4aa6-830f-8570999238a2.png)

Also check your keybindings for any binding using shift+h etc (these bindings stop the keys being sent to VSCode-Neovim).

For example

![image](https://user-images.githubusercontent.com/51082452/217479181-881bda1e-3e76-469c-9354-603240aad746.png)

Which would look like this in the _Keyboard Shortcuts_ tab in VSCode

![image](https://user-images.githubusercontent.com/51082452/217479534-ba0f95c0-e544-4b4a-981f-287072d88f6f.png)

Incidentally, this is how you would create the keymappings in VSCode (by-passing VSCode-Neovim).

Let me know how you go :)

**Comment by ctstacey** [comment]
FYI for future readers,
with freash installs of VSCode 1.75, Neovim 0.8.3, VSCode-Neovim 0.97

These mappings should work in your init.vim without any other setup
> ```vim
> nnoremap <S-h> <Cmd>call VSCodeNotify('workbench.action.previousEditor')<CR>
> nnoremap <S-l> <Cmd>call VSCodeNotify('workbench.action.nextEditor')<CR>
> ```

Normally I prefer to define the mappings in init.vim, because mappings in VSCode's keybindings.json prevent those key combinations being sent to Neovim.

However, for this particular situation, mapping in VSCode keybindings.json has the advantage that it will work even when not in an editor windows. For example, it will still work when in the _Settings_ or _Keyboard Shortcuts_ windows (tabs).
