### ISSUE TITLE
feature: option to disable the synchronization of mouse selections

### ISSUE THREAD

**Issue by BTBMan** [vscode-neovim/vscode-neovim#1475]
### Did you check the docs?

- [X] I have read all the vscode-neovim docs
- [X] I understand the fundamental limitations of the plugin and believe this request to be reasonable

### Is your feature request related to a problem? Please describe.

After v0.3.2, It syncs visual selections with VSCode and synchronizes mouse selections. but it's not very comfortable to use. It has some problems sometimes. E.g. The cursor position syncs very slowly when selecting using the mouse, The visual selection is not correct after selecting.

In the terminal, It doesn't synchronize mouse selections by default.

I know the VSCodeVim has this feature, And that's one of the reasons I didn't use it. It's hard to use for me.

### Describe the solution you'd like

I hope to add a VSCode option to switch the synchronization of mouse selections.

### Describe alternatives you've considered

I don't have.

**Comment by xiyaowong** [comment]
> The visual selection is not correct after selecting.

Actually, this is caused by a synchronization problem with the viewport.

> In the terminal, It doesn't synchronize mouse selections by default.

As far as I know, a terminal is not a text editor and is not handled by vscode-neovim at all.

> I hope to add a VSCode option to switch the synchronization of mouse selections.

It is possible to add that option, and I also think that synchronizing the mouse selection is not very useful.

TODO:

- option to toggle mouse selection
- option to change the debounce time for synchronizing the mouse selection

**Comment by justinmk** [comment]
Ideally we should avoid adding an option and just make a decision about the best builtin behavior.

**Comment by xiyaowong** [comment]
If the user wants to disable a certain feature, it seems that the only option is to add a new option.

**Comment by theol0403** [comment]
> Ideally we should avoid adding an option and just make a decision about the best builtin behavior.

Yeah, this was my original approach. I thought that since VSCode was a graphical program to start with, mouse support should continue to be first-class. Ignoring the mouse seemed to me like something only desirable in a TUI.

Additionally, the code that syncs the mouse, isn't actually specific to the mouse at all. Instead, it syncs vscode selections to nvim.

The way the sync works is that whenever a vscode selection is updated, it waits a bit for debouncing, then compares with the exisitng visual mode in nvim, and sends nvim into visual mode if there is a mismatch.

If people really want to ignore the mouse, you'd have to *add* logic that ignores the vscode selection changed event when the source is from a mouse and the selection range > 1.
