### ISSUE TITLE
bug: Scrambled and overlapping code NVIM v0.9.1

### ISSUE THREAD

**Issue by benlieb** [vscode-neovim/vscode-neovim#1740]
### Did you check docs and existing issues?

- [X] I have read all the vscode-neovim docs
- [X] I have searched the existing issues of vscode-neovim
- [X] I can reproduce the issue with an empty init.vim/init.lua and no other vscode extensions (when applicable)

### Neovim version (nvim -v)

NVIM v0.9.1 Build type: Release LuaJIT 2.1.0-beta3

### Operating system/version

Mac 13.2.1 (22D68)

### Describe the bug

I'm trying hard to switch from plain nvim to neovim in VSCode. I have persistent issues with code being scrambled and unreadable, and github copilot suggestions also being scrambled and and unusable (using tab, just makes a tab instead of selecting when scrambled)

![image]( https://github.com/vscode-neovim/vscode-neovim/assets/634562/e08e8010-0746-4937-8aea-03aecb22095c)

I looked through the issues, and I can't tell if this is a common issue with a commons solution. I've tried disabling my entire vimrc file, but that seemed to have no effect. I've also tried disabling other vscode extensions (ones that seemed reasonable that might have an effect), but that also seemed to have no effect. I will now actually disable all 60 and see what that does. 

Please help! And thank you for your great work!

### Steps To Reproduce

This happens randomly from my perspective, but several times a minute. My solution is to switch tabs and come back.

### Expected Behavior

For the code to never look scrambled and github copilot to work as intended via `tab`.

**Comment by benlieb** [comment]
Might be coming from my plugins directory in nvim?

**Comment by justinmk** [comment]
try enabling the `vscode-neovim.neovimClean` setting and restart vscode

**Comment by panpanpro888** [comment]
I was also having an issue with overlapping characters and removing my theme from my plugins seems to solve the issue.
Here is the theme i was using.
```lua
return {
    'catppuccin/nvim',
    name = 'catppuccin',
    lazy = false,
    priority = 1000,
    config = function()
        require('catppuccin').setup {
            color_overrides = {
                all = {
                    base = '#11111b',
                },
            },
            custom_highlights = function(C)
                return {
                    CmpItemKindSnippet = { fg = C.base, bg = C.mauve },
                    CmpItemKindKeyword = { fg = C.base, bg = C.red },
                    CmpItemKindText = { fg = C.base, bg = C.teal },
                    CmpItemKindMethod = { fg = C.base, bg = C.blue },
                    CmpItemKindConstructor = { fg = C.base, bg = C.blue },
                    CmpItemKindFunction = { fg = C.base, bg = C.blue },
                    CmpItemKindFolder = { fg = C.base, bg = C.blue },
                    CmpItemKindModule = { fg = C.base, bg = C.blue },
                    CmpItemKindConstant = { fg = C.base, bg = C.peach },
                    CmpItemKindField = { fg = C.base, bg = C.green },
                    CmpItemKindProperty = { fg = C.base, bg = C.green },
                    CmpItemKindEnum = { fg = C.base, bg = C.green },
                    CmpItemKindUnit = { fg = C.base, bg = C.green },
                    CmpItemKindClass = { fg = C.base, bg = C.yellow },
                    CmpItemKindVariable = { fg = C.base, bg = C.flamingo },
                    CmpItemKindFile = { fg = C.base, bg = C.blue },
                    CmpItemKindInterface = { fg = C.base, bg = C.yellow },
                    CmpItemKindColor = { fg = C.base, bg = C.red },
                    CmpItemKindReference = { fg = C.base, bg = C.red },
                    CmpItemKindEnumMember = { fg = C.base, bg = C.red },
                    CmpItemKindStruct = { fg = C.base, bg = C.blue },
                    CmpItemKindValue = { fg = C.base, bg = C.peach },
                    CmpItemKindEvent = { fg = C.base, bg = C.blue },
                    CmpItemKindOperator = { fg = C.base, bg = C.blue },
                    CmpItemKindTypeParameter = { fg = C.base, bg = C.blue },
                    CmpItemKindCopilot = { fg = C.base, bg = C.teal },
                }
            end,
        }
        vim.cmd [[colorscheme catppuccin-mocha]]
    end,
}
```

**Comment by xiyaowong** [comment]
Need:
1. A screen recording that includes the steps to reproduce the issue.
2. If possible, please provide your configuration.

**Comment by xiyaowong** [comment]
@panpanpro888  Can you tell me which plugins you use?

**Comment by panpanpro888** [comment]
I used to use:
- [Catppuccin](https://github.com/catppuccin/nvim)
- [Telescope](https://github.com/nvim-telescope/telescope.nvim)
- [Nvim-tree](https://github.com/nvim-tree/nvim-tree.lua)
- [LSP Config](https://github.com/neovim/nvim-lspconfig)
- [Mason](https://github.com/williamboman/mason.nvim)
- [Mason LSP Config](https://github.com/williamboman/mason-lspconfig.nvim)
- [Nvim CMP](https://github.com/hrsh7th/nvim-cmp)
- [CMP LSP](https://github.com/hrsh7th/cmp-nvim-lsp)
- [CMP Path](https://github.com/hrsh7th/cmp-path)
- [CMP Buffer](https://github.com/hrsh7th/cmp-buffer)
- [LuaSnip](https://github.com/L3MON4D3/LuaSnip)
- [CMP LuaSnip](https://github.com/saadparwaiz1/cmp_luasnip)
- [TreeSitter](https://github.com/nvim-treesitter/nvim-treesitter)
- [Dressing](https://github.com/stevearc/dressing.nvim)
- [Which Key](https://github.com/folke/which-key.nvim)
- [Emmet](https://github.com/mattn/emmet-vim)
- [CMP Emmet](https://github.com/dcampos/cmp-emmet-vim)
- Markdown Viewer (I don't remember the link)
- [Nvim Surround](https://github.com/kylechui/nvim-surround)
- [Alpha](https://github.com/goolord/alpha-nvim)
- [LuaLine](https://github.com/nvim-lualine/lualine.nvim)
- [LuaLine Time](https://github.com/archibate/lualine-time)
- [Crates](https://github.com/Saecki/crates.nvim)
- [None LS](https://github.com/nvimtools/none-ls.nvim)
- [Vim Tmux Navigator](https://github.com/christoomey/vim-tmux-navigator)
- [Presence](https://github.com/andweeb/presence.nvim)
- [DAP](https://github.com/mfussenegger/nvim-dap)
- [Mason DAP](https://github.com/jay-babu/mason-nvim-dap.nvim)
- [QuickMath](https://github.com/jbyuki/quickmath.nvim)

But my neovim was bloated so I rewrote my config with:
- [Oil](https://github.com/stevearc/oil.nvim)
- [LSP Config](https://github.com/neovim/nvim-lspconfig)
- [Nvim CMP](https://github.com/hrsh7th/nvim-cmp)
- [CMP LSP](https://github.com/hrsh7th/cmp-nvim-lsp)
- [Fzf](https://github.com/junegunn/fzf.vim)
- [Catppuccin](https://github.com/catppuccin/nvim)
- [TreeSitter](https://github.com/nvim-treesitter/nvim-treesitter)
- [Crates](https://github.com/Saecki/crates.nvim)
- [Vim Tmux Navigator](https://github.com/christoomey/vim-tmux-navigator)

Now the issue is solved. I don't know which plugin caused the issue 😅.

**Comment by xiyaowong** [comment]
Do not use LSP plugins or completion plugins.
