### ISSUE TITLE
Plugins not loading (or inoperable) with lazy.nvim

### ISSUE THREAD

**Issue by benlieb** [vscode-neovim/vscode-neovim#1756]
### Did you check docs and existing issues?

- [X] I have read all the vscode-neovim docs
- [X] I have searched the existing issues of vscode-neovim
- [X] I can reproduce the issue with an empty init.vim/init.lua and no other vscode extensions (when applicable)

### Neovim version (nvim -v)

0.9

### Operating system/version

Macos 13.2.1

### Describe the bug

The plugins I'm loading with lazy.nvim work in neovim, but are not working (or loading) in vscode:

### Steps To Reproduce

```lua
local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "https://github.com/folke/lazy.nvim.git",
    "--branch=stable", -- latest stable release
    lazypath,
  })
end
vim.opt.rtp:prepend(lazypath)

require("lazy").setup({
  'tpope/vim-commentary',
  'jeetsukumaran/vim-indentwise',
  'mattn/emmet-vim',
  {
    'arthurxavierx/vim-caser',
    init = function()
      vim.g.caser_prefix = ',vc'
    end,
  },
  'michaeljsmith/vim-indent-object',
  'adelarsq/vim-matchit',
  'tpope/vim-rails',
  'tpope/vim-repeat',
  'tpope/vim-surround',
  'rhysd/vim-textobj-ruby',
  'kana/vim-textobj-user',
  'bronson/vim-visual-star-search',
  'dyng/ctrlsf.vim',
  'junegunn/vim-easy-align',
  'vim-test/vim-test',
})
```
### Expected Behavior

I would expect, for example `S"` a word with double quotes when selected. Is there a compatibility issue with lazy.nvim, or is there some config option(s) I need to set?

**Comment by BrunoLadiv** [comment]
Try to change ur keybind i use vim.keymap.set('x', 'ys', '<Plug>VSurround', { silent = true })
cus S is set for leap

**Comment by xiyaowong** [comment]
Are all plugins unable to load or is it just vim-surround?

**Comment by benlieb** [comment]
No plugins seem to be loading.

**Comment by mbhutton** [comment]
@benlieb In order to see which plugins are loading in terminal neovim vs in VSCode, you could try adding this at the end of your `init.lua`:
```
local function print_plugins()
  local plugins = require("lazy").plugins()
  for _, plugin in pairs(plugins) do
    if plugin.url ~= nil then
      print(plugin.url .. "\n")
    end
  end
end
print_plugins()  -- Comment or uncomment to toggle the output
```

After making this change:

- On the terminal version, run `nvim --headless +qa` to get just the urls of loaded lazy plugins. 
- Restart VSCode, then `Focus on Output View`, selecting the `vscode-neovim` process in the toggle on top right, which should now show the plugins loaded by lazy.

I've been doing that to figure out why certain plugins weren't loading in VSCode.

I'm also using lazy.vim, but as part of a close-to-vanilla LazyVim, and plugins are indeed loading in VSCode. In that setup, plugins seem to load by default in VSCode, until the [VSCode extra](https://www.lazyvim.org/extras/vscode) is enabled, at which point most plugins become implicitly "opt-in". Opt-in meaning that you need to set `vscode=true` (or an alternative like `cond = true`) for any plugin spec that you also wan't to load in VSCode.

In any case, capturing that output from both environments should make it clear whether it's failure to load the plugins at all vs some incompatibility specific to the plugins themselves.

**Comment by xiyaowong** [comment]
I'm not sure if this is an issue with vscode-neovim. You can provide a screen recording with steps to check if the plugin is loaded

Try: `:lua =require("lazy").plugins()`

**Comment by benlieb** [comment]
At this point I'm not even sure that the extension is loading my init file at all. I tried to confirm this with just the init.lua file, but I'm at a loss for finding out how to debug this.

I tried also with a near empty init.vim file. Still seems to not be loading...

![image](https://github.com/vscode-neovim/vscode-neovim/assets/634562/e80da2c6-fc82-4ad9-ac99-3199c3fa19af)

**Comment by xiyaowong** [comment]
@benlieb  Run `:echo stdpath('config')` in vscode

**Comment by rollysys** [comment]
I have the same issue too

**Comment by justinmk** [comment]
I think vscode-neovim should print `stdpath('config')` and other info in its Output channel on startup.

**Comment by justinmk** [comment]
> I think vscode-neovim should print `stdpath('config')` and other info in its Output channel on startup.

Progress towards that: https://github.com/vscode-neovim/vscode-neovim/pull/1786
