### ISSUE TITLE
How to disable auto-switching to
Neovim Output

### ISSUE THREAD

**Issue by shelper** [vscode-neovim/vscode-neovim#1812]
I found that when there's an error from using this extension, 
Vscode automatically switch to the extension output panel, is there a way to disable that?
Did some research but could not figure out..

*UPDATE*
even after setting loglevel to None, i still get output from neovim in vscode output window

my vscode version: 1.86.1, 
neovim version is the latest, 1.6.1
This happens when using using vscode for windows project, and the neovim in wsl. 
i am using vscode on windows remote to wsl, then no problem

**Comment by justinmk** [comment]
👍  Meanwhile as a workaround, try setting log level to "none".

<img width="671" alt="image" src="https://github.com/vscode-neovim/vscode-neovim/assets/1359421/9b80e7c0-b7ef-4687-a3fc-f3ec21a1b0f0">

**Comment by justinmk** [comment]
What exact steps are you doing? What does the Output channel show? The only code that I see that currently calls `show()` is here: https://github.com/vscode-neovim/vscode-neovim/blob/7cc80508dccf2e52ffac6484e45dcec32ec76fc4/src/messages_manager.ts#L40-L58

and that only happens if you send a command to Nvim such as `:messages`, `:ls`, etc (things that _should_ show the output).

**Comment by justinmk** [comment]
> _UPDATE_
> even after setting loglevel to None, i still get output from neovim in vscode output window

_What steps_ exactly are you taking that I can follow to reproduce this issue? 

What exactly do you mean by "i still get output"? Is the Output view being switched-to on vscode startup? Or are you running a Nvim command (in that case, the Output view is intentionally shown, because the output needs to be displayed somewhere...).
