### ISSUE TITLE
bug: Composite escape keys not working with macros

### ISSUE THREAD

**Issue by pypp** [vscode-neovim/vscode-neovim#1959]
### Check the following:

- [X] I have checked the behavior after setting "vscode-neovim.neovimClean" in VSCode settings.
- [X] I have read the vscode-neovim docs.
- [X] I have searched existing issues.

### Neovim version (nvim -v)

0.9.4

### Operating system/version

Windows 10 Home

### Describe the bug

When recording macros (clicking q) the composite key doesn't work.
After the breaking changes I added the new `vscode-neovim.compositeKeys` to the `settings.json` but that seems to not have effect when recording macros, I click on the configured keys to exit  edit mode but instead it just types out the keys.

### Steps To Reproduce

1. add `vscode-neovim.compositeKeys` like stated in the `README.md` file.
2. start recording macros (press q)
3. try to exit edit mode with the configured keys

### Expected Behavior

To exit to normal mode

**Comment by xiyaowong** [comment]
In macro recording mode, please use `<esc>` or `<Ctrl+]>` to exit insert mode, or add `inoremap jj <esc>` to your init.vim. During macro recording, input is entirely controlled by nvim (you may notice that at this time, vscode won't provide any autocomplete suggestions). 

It could be argued that this is by design, or it could be said that this is an unavoidable flaw in vscode-neovim.
