### ISSUE TITLE
bug: output panel opens automatically for failed searches

### ISSUE THREAD

**Issue by mkaminsky** [vscode-neovim/vscode-neovim#2046]
### Check the following:

- [X] I have checked the behavior after setting "vscode-neovim.neovimClean" in VSCode settings.
- [X] I have read the vscode-neovim docs.
- [X] I have searched existing issues.

### Neovim version (nvim -v)

v0.10.0-dev-3080+gefb44e0ca

### Operating system/version

Linux Debian testing

### Describe the bug

Starting with v1.14.0 (PR #2029):  If you search for text (using / in normal mode) that does not exist in the buffer, the output panel opens automatically.  I find this somewhat jarring given how frequent it is to have no search results.

Is it possible to make that optional (as discussed in the PR)?

Thanks!

### Steps To Reproduce

1. Create / open a file.
2. Type some text, e.g., "abcdef"
3. In normal mode, type / to begin searching.
4. Enter "zzz" into the "Forward Search" field.
5. Output panel opens showing: `E486: Pattern not found: zzz`

### Expected Behavior

Don't open the output panel automatically (at least for failed searches).

**Comment by mschwartz** [comment]
LOL.  Annoying bug.  I have my terminal and output tabs in the same right side panel.  It's constantly activating the output tab thus hiding the terminal one.  There's no place to move either to make my workflow satisfactory...

Maybe me and hundreds of other users are spending a lot of time looking for a solution to fix this :)

**Comment by xiyaowong** [comment]
@ollien It seems that this has already been checked here.
https://github.com/vscode-neovim/vscode-neovim/blob/898ad178bd8b980fc45007f95829145ba542627b/src/messages_manager.ts#L43-L45
So ignoring the return_prompt is expected. 😂

**Comment by ollien** [comment]
@xiyaowong this was a separate change from that. The thing is that if you have output that is only one line, it looks like nothing happens and you don't see your output. 

I'm surprised not finding a match sends us a `return_prompt`, that sounds inconsistent with normal nvim, but I am not able to investigate immediately.

**Comment by ollien** [comment]
> The output when search match not found is two lines long. FWIW.

Interesting, because the two lines long check is not new.

**Comment by mschwartz** [comment]
Maybe it’s a change to neovim itself?

I any case, can we fix this?  It is making vs code almost unusable….

thanks

**Comment by ollien** [comment]
Yes, I will investigate when I get a spare cycle. You are welcome to downgrade to an earlier release in the interim :)

**Comment by ollien** [comment]
Blargh. I finally got some time to investigate this and it is more thorny than I thought. The short answer is, this didn't happen before because the output would show if there were _three_ lines or more, and would ignore `return_prompt`. Now, we display on _two_ lines or more, or a `return_prompt.` Unfortunately, a failed search exhibits both of these properties


```
[
	["wmsg", [[98, "search hit BOTTOM, continuing at TOP"]], true],
	["emsg", [[78, "E486: Pattern not found: alsdkfjasdlkfjd"]], false],
	["return_prompt", [[152, "Press ENTER or type command to continue"]], false]
]
```

I need to investigate why this specific case sends us a `return_prompt`, as doing this in neovim does not give me a "Press ENTER or type command to continue" prompt. Once I do that, I can think more deeply about how to handle the message display. I have a couple of ideas. Stay tuned. Thanks for your patience.

**Comment by ollien** [comment]
Some investigative work later: I've figured out a couple things

1. The "search hit BOTTOM, continuing at TOP" message that you see above is actually not sent with our default settings (you may be able to tell I've been messing around a bit with `shortmess` options :sweat_smile:)
2. I figured out why this doesn't happen in plain `nvim`: by using `ext_messages`, we opt into a [separate code path](https://github.com/neovim/neovim/blob/3a1515bfee59710b4da9bfdf0fc4ecb5b13a00db/src/nvim/message.c#L2079-L2083) for determining if the `press-enter` prompt should be shown; if more than one line is being displayed, it shows the `press-enter` prompt. Unfortunately, the literal command line (`/abcde`) counts towards this "count", so that line plus the error message results in a `return_prompt` being sent to us. Very frustrating; I certainly wouldn't have expected this behavior, but struggle to go so far as to call it a bug.

Given this, I'm tempted to just revert #2029, which is disappointing because in principle it actually delivers some value (e.g. `!` commands will show their output automatically). I'll take a bit more time to see if there's a solution, but I'm not hopeful.

**Comment by iansinnott** [comment]
A note to future readers. I was still seeing this undesirable behavior in `v1.15.2` but was using nvim `9.x`. Upgrading neovim seems to have resolved the issue. Not sure why, just something to note if anyone is still seeing this bug.

**Comment by ollien** [comment]
@iansinnott That's a really interesting finding! It looks like on nvim 0.9.x, we are sent two lines like I noted here https://github.com/vscode-neovim/vscode-neovim/issues/2046#issuecomment-2144072174. This explains why the behavior went away for me, I must have changed over to 0.10 somewhere in there. 

For now, you can work around this with `set shortmess+=s` to prevent the "search hit BOTTOM continuing at TOP" message from appearing. I'll probably add this to the README

**Comment by still-dreaming-1** [comment]
I had to set the "vscode-noevim logs" channel from the OUTPUT panel to "Warning" or lower to fix this issue in my VSCode. Maybe this will help someone else that ends up here.
