### ISSUE TITLE
bug: "requires nvim version ..." message is unclear when user has nvim 0.10.0-dev (prerelease)

### ISSUE THREAD

**Issue by LucienMorey** [vscode-neovim/vscode-neovim#2225]
### Check the following:

- [X] I have checked the behavior after setting "vscode-neovim.neovimClean" in VSCode settings.
- [X] I have read the vscode-neovim docs.
- [X] I have searched existing issues.

### Neovim version (nvim -v)

NVIM v0.10.0

### Operating system/version

Ubuntu 24.04.1

### Describe the bug

Opening vscode triggers a false positive error stating I have not met the minimum version to use the extension. I can still use the extension, but the pop-up is annoying.

![image](https://github.com/user-attachments/assets/5cdefffd-0d39-4210-a117-d007e346451a)

I am running the snap installation of nvim if it makes any difference.

I have yet to try any other installation format to see if the error disappeared.

### Steps To Reproduce

Open vscode

### Expected Behavior

I am not expecting an error to appear because I meet the stated version requirement

**Comment by justinmk** [comment]
this `lt()` should be changed to `le()` https://github.com/vscode-neovim/vscode-neovim/blob/90b4ff3a147c772a8b417d2763483feef94a1a76/runtime/vscode-neovim.vim#L31

**Comment by justinmk** [comment]
> I am running the snap installation of nvim if it makes any difference.

Possibly some sort of issue with the runtime files. 

What does `:lua =vim.version.parse` show from nvim?

**Comment by fernandoalexandre** [comment]
Disclaimer, I'm not the biggest expert in lua, but it seems it's related to this code:

https://github.com/vscode-neovim/vscode-neovim/blob/90b4ff3a147c772a8b417d2763483feef94a1a76/runtime/vscode-neovim.vim#L25
`local MIN_VERSION = vim.g.vscode_nvim_min_version

local outdated = not (vim.version and vim.version.parse)
if not outdated then
  local cur = vim.version()
  local min = vim.version.parse(MIN_VERSION)
  outdated = vim.version.lt(cur, min)
end`

where the latest version increase to 0.10.0.

In the logic above, at least in my nvim (in osx) the outdated will be `false` as those variables only point to a function and not the version value it seems.

Afterwards it enters the `if not outdated` section where only versions higher than the minimum are accepted, and now it's the same version, it seems it should be `outdated = vim.version.le(cur, min)` instead of `lt`

**Comment by fernandoalexandre** [comment]
Deleted my previous post as the logic should be correct reviewing the code after a while.

Was experimenting a bit more on nvim in ubuntu WSL on the piece of code:
https://github.com/vscode-neovim/vscode-neovim/blob/90b4ff3a147c772a8b417d2763483feef94a1a76/runtime/vscode-neovim.vim#L29

```
:lua =vim.version()
{
  api_compatible = 0,
  api_level = 12,
  api_prerelease = vim.NIL,
  build = "v0.10.0",
  major = 0,
  minor = 10,
  patch = 0,
  prerelease = "dev",
  <metatable> = {
    __eq = <function 1>,
    __index = <function 2>,
    __le = <function 3>,
    __lt = <function 4>,
    __newindex = <function 5>,
    __tostring = <function 6>
  }
}

:lua =vim.version.parse("v0.10.0")
{
  major = 0,
  minor = 10,
  patch = 0,
  <metatable> = {
    __eq = <function 1>,
    __index = <function 2>,
    __le = <function 3>,
    __lt = <function 4>,
    __newindex = <function 5>,
    __tostring = <function 6>
  }
}
```

If I run the following code similar to the one being used:
```
:lua =vim.version.lt(vim.version(), vim.version.parse("0.10.0"))
> true
```

which should definitely be `false` since they should be the same version (using the parse with `v0.10.0` yields the same result), however:

```
:lua =vim.version.lt(vim.version.parse(vim.version().build), vim.version.parse("0.10.0"))
> false
```

as expected, seems like there is a caveat when using the `vim.version.lt` comparison with the full `vim.version()` object.

**Comment by justinmk** [comment]
Thanks for testing that.

> it seems nvim also takes into account the `prerelease` which in the `snap` and homebrew versions of nvim is 'dev'.

Yes, and Nvim is doing the correct thing here. Question is why snap does not have the final release? "dev" means it could be any commit before the release.

Some improvements we can make in vscode-neovim:

1. mention the prerelease name and request that the user gets the final release

**Comment by LucienMorey** [comment]
Thanks for looking at this so quickly! I didn't expect anything by the time I woke up. To mitigate the issue, I have moved from the snap to the latest app image on your suggestion anyway.

**Comment by faea726** [comment]
Hey. I got the same issue here on Windows 11.
nvim and VsCode installed directly on Windows 11.

```
nvim -v
VIM v0.10.0
Build type: Release
LuaJIT 2.1.1713484068
Run "nvim -V1 -v" for more info
```

VSCode Neovim version: `v1.18.11`

**Comment by justinmk** [comment]
@faea726 your comment shows nvim v0.10.0. update to nvim v0.10.1, as explained already in the comments above.

**Comment by faea726** [comment]
> @faea726 your comment shows nvim v0.10.0. check `:lua =vim.version()` to see the `prerelease` field.
> 
> update to nvim v0.10.1, as explained already in the comments above.

Worked. Thank you.
