### ISSUE TITLE
bug: Visual mode unexpectedly entered when keyboard navigating between Find in Files results

### ISSUE THREAD

**Issue by aguynamedben** [vscode-neovim/vscode-neovim#2270]
### Check the following:

- [X] I have tried setting `vscode-neovim.neovimClean` in VSCode settings and **restarting VSCode.**
- [X] I have read the vscode-neovim docs.
- [X] I have searched existing (closed!) issues.

### Neovim version (nvim -v)

NVIM v0.10.1

### Operating system/version

macOS Sonoma 14.2.1

### Problem (including [log messages](https://github.com/vscode-neovim/vscode-neovim?tab=readme-ov-file#troubleshooting))

After performing a Find in Files search, when using F4 (references-view.next) and Shift+F4 (references-view.prev) to navigate between results, I'm unexpectedly put into Visual mode. This does not happen when using the mouse to navigate—only when using the keyboard shortcuts or the `references-view.next`/`references-view.prev` commands.

### Steps To Reproduce

1. Have a stock VS Code install with `vscode-neovim.neovimClean` in settings.
2. Install vscode-neovim plugin
3. Open a codebase
4. Hit Cmd+Shift+Enter to Find in Files
5. Type a query
6. Hit F4 a few times to navigate to a result in an editor (Fn+F4 on a Mac)
**Expected:** Hitting j or k would navigate around the editor
**Actual:** Hitting j or k begins highlighting because for some reason we've been put into Visual mode.

Video: https://www.dropbox.com/scl/fi/e5i11kkm1an3um8itzy9c/unexpected-visual-mode.mp4?rlkey=a44d3fki6xul79be9xeh25hr4&st=yahplyyb&dl=0

The logs don't have any errors

```
2024-09-28 01:51:47.105 [info] MainController: Starting nvim: /opt/homebrew/bin/nvim -N --embed --cmd source /Users/ben/.vscode/extensions/asvetliakov.vscode-neovim-1.18.12/runtime/vscode-neovim.vim --clean
2024-09-28 01:51:47.152 [info] MainController: Nvim info: {
  nvimVersion: {
    api_compatible: 0,
    major: 0,
    minor: 10,
    patch: 1,
    build: null,
    prerelease: false,
    api_level: 12,
    api_prerelease: false
  },
  logFile: '/Users/ben/.local/state/nvim/log',
  configDir: '/Users/ben/.config/nvim'
}
```

(and nothing in vscode-neovim message)

### Expected Behavior

I would expect to be able to use F4 to go to each result within its editor, then navigate around in Normal mode. I think it's a bug that it's putting me into the editor in Visual mode.

Thank you for this fantastic plugin!!! It's making VS Code and Cursor very nice to use!

**Comment by theol0403** [comment]
This is caused because *vscode* is putting us in visual mode -- by "selecting" the text corresponding to the match in the buffer. There is no way of telling the difference between an intentional selection (eg `editor.action.smartSelect.expand`) or a selection made from the find window. Since selecting text puts nvim in visual mode, there is no good solution.

- this has been reported here before. try searching and see if there was any resolution
- see if there is a setting to remove this behavior in vscode (to preselect the result)
- see if there is a way to hack some solution like binding F4 to next result + send escape to nvim
