### ISSUE TITLE
bug: visual mode remains after canceling vscode search

### ISSUE THREAD

**Issue by wenfangdu** [vscode-neovim/vscode-neovim#2307]
### Check the following:

- [X] I have tried setting `vscode-neovim.neovimClean` in VSCode settings and **restarting VSCode.**
- [X] I have read the vscode-neovim docs.
- [X] I have searched existing (closed!) issues.

### Neovim version (nvim -v)

0.10.2

### Operating system/version

macOS 15

### Problem (including [log messages](https://github.com/vscode-neovim/vscode-neovim?tab=readme-ov-file#troubleshooting))

In normal mode, use`actions.find` to search, then press `esc`, neovim visual mode remains which it shouldn't.

### Steps To Reproduce

https://github.com/user-attachments/assets/23045650-1a0d-4439-b4b0-6e327acf86ff

### Expected Behavior

After canceling vscode search, neovim enters normal mode.

**Comment by lattaai1** [comment]
Hello, I've fixed this issue!

This is what I've done:
I have updated the `handleModeChanged` method in the `ModeManager` class to properly handle the transition from visual mode to normal mode when the VSCode search is canceled. This change ensures that the Neovim visual mode is correctly exited when the user cancels the VSCode search.

I also created pull request: https://github.com/vscode-neovim/vscode-neovim/pull/2308


> [!CAUTION]  
> Disclaimer: This fix was created by Latta AI and you should never merge before you check the correctness of generated code!

---
This bug was fixed for free by Latta AI - https://latta.ai/ourmission

**Comment by wenfangdu** [comment]
@xiyaowong Actually, not a dup of #2299, this is the expected behavior, since in insert mode, the selection also stays after using `esc`, I solved it using:

```json
{
  "key": "escape",
  "command": "runCommands",
  "args": {
    "commands": ["closeFindWidget", "vscode-neovim.escape"]
  },
  "when": "findWidgetVisible"
}
```
