### ISSUE TITLE
feature: show status in floating window

### ISSUE THREAD

**Issue by MahdiNazemi** [vscode-neovim/vscode-neovim#2323]
### Did you check the docs?

- [X] I have read all the vscode-neovim docs
- [X] I understand the fundamental limitations of the plugin and believe this request to be reasonable

### Is your feature request related to a problem? Please describe.

VSCode has support for [floating windows](https://code.visualstudio.com/docs/getstarted/userinterface#_floating-windows) where you can move a file or group of files to a separate window. Currently, the output of Vim commands are printed in the status bar of the main window, which may be minimized, hidden, etc.

### Describe the solution you'd like

It would be useful to have an option to show the output of commands in the status bar of the (floating) window where they are run from.

**Comment by justinmk** [comment]
> in the status bar of the editor group where the command was run from instead of the main window.

Oh I see, that clarifies the idea. I think this would require vscode-neovim to declare its statusbar item as "document specific" (in the vscode API this implies a `right` position instead of `left`). Then it would appear in the floating window, if this screenshot maps to what you mean (else show a screenshot of what you mean):

![image](https://github.com/user-attachments/assets/c15949d8-9dd3-4718-a67d-dfd450d189a3)

But that would technically violate vscode's UX guidelines, since vscode-neovim status is "global", not document-specific.

**Comment by justinmk** [comment]
> I was hoping there was a way to show the commands and outputs at the bottom left.

I haven't looked, but maybe vscode has a setting that enables the left-side status items for its floating editors.
