### ISSUE TITLE
Proposal: Logo

### ISSUE THREAD

**Issue by ngscheurich** [vscode-neovim/vscode-neovim#325]
As I [mentioned](https://github.com/asvetliakov/vscode-neovim/issues/319#issuecomment-680289048) in #319, I propose changing the name of this extension to something that stands alone, i.e. not _Neo Vim_ or _Neovim_, and developing a logo for the project. I designed a logo for my suggested name—_NeoCode_—and I thought I'd share it to get some feedback. The idea was to re-create the VS Code logo while borrowing some design elements from the Neovim logo.

I understand that this name and/or design may not be something that the community is into, but I wanted to share in case it is helpful.

Thoughts?

![neocode-logo](https://user-images.githubusercontent.com/423798/91239009-f2a46680-e703-11ea-901c-f3d650bc2381.png)

**Comment by asvetliakov** [comment]
Awesome work, love this one. Probably need a square one for marketplace

**Comment by ngscheurich** [comment]
Glad you like it! I submitted a PR, #327,  with a slightly revised version in case you want to go ahead and use it.

**Comment by David-Else** [comment]
This looks amazing! The only problem I can see is that the word 'vim' is no longer in the title. Many people who are looking for Vim shortcuts may not know about Neovim and not get the reference. Maybe if there was a strong tag line used everywhere the logo appeared this could reduce the problem? How about this?
```
NeoCode - Code at the speed of thought | Native Neovim integration for Visual Studio Code.
```

**Comment by ngscheurich** [comment]
That's a really good point, @David-Else. I think using "Native Neovim integration for Visual Studio Code." as the `description` property in `package.json` is a great idea, regardless of what the name ends up being.

**Comment by ngscheurich** [comment]
If we do end up using the moniker I suggested, we should keep the "c" lower case—_Neocode_—to better match up with _Neovim._ Just a thought.

**Comment by ian-h-chamberlain** [comment]
Found this issue and just wanted to add another perspective to the conversation:

If you Google "Neocode" the first result appears to be a software company by that name: https://www.neocode.com/

I have no legal expertise so don't know if there is any problem with using the same name. The company seems different enough from this project that there would be little opportunity for confusion – but I wouldn't want to see this project to suffer because of a name collision like that.

That said, I love the logo and styling and think it complements the VSCode and Neovim designs quite nicely. So if there is no issue with the name collision I think it should still be used.

**Comment by theol0403** [comment]
As of #513, the plugin is now called "VSCode Neovim". This was simply something small I added to the PR, and no one seemed to mind, so it has been merged. 

I'm sure the name could still be changed if people have a better idea. I personally think NeoCode isn't ideal, simply because I discovered this extension by searching "VIM". 

However, a better slogan to go in the github description and top of the readme might be nice! Even something like "Native Neovim integration for Visual Studio Code." is probably better than "VSCode Neovim Integration" (what it is currently).
