### ISSUE TITLE
Chinese bug

### ISSUE THREAD

**Issue by andyliumathematics** [vscode-neovim/vscode-neovim#697]
From command mode to Insert mode,I insert 'A'.When my insert method is Chinese(for example sougou insert method https://ime.sogouimecdn.com/202107140931/e45e9d1200ca0f9de985d0a67428bec1/dl/index/1625066038/sogou_pinyin_105b.exe?f=pinyinbanner&dcs=13fa4317e1dccdcb83b3cf626d474c77),it Jumps to the end of the line(it is right).bug it inserts 'A',to the end of the line(the bug).
The vim is right(No 'A' at the end of the line).

**Comment by echaya** [comment]
>From command mode to Insert mode,I insert 'A'.When my insert method is Chinese(for example sougou insert method
do you mean from normal mode to insert mode? If that is the case, I can repro.
my understanding is when having Chinese IME enabled, any typing will be sent to the IME instead of app layer (VIM or VSCODE). So it makes a lot of sense to switch off Chinese IME in normal mode, only switch back to Chinese IME in insert mode (when needed)

**Comment by andyliumathematics** [comment]
I know swithing can solve the ploblem. but vim plugin does not hive this bug.

>

**Comment by evolify** [comment]
any update?

**Comment by xiyaowong** [comment]
I have never encountered this problem before. If the problem still exists, please open it again.
