### ISSUE TITLE
Be able to run wsl from a 32 bit vscode

### ISSUE THREAD

**Issue by zero-element** [vscode-neovim/vscode-neovim#769]
I got the following error:

> Unable to init vscode-neovim: Command failed: C:\Windows\system32\wsl.exe wslpath 'c:\\Users\\%USERNAME%\\.vscode\\extensions\\asvetliakov.vscode-neovim-0.0.82' 'C:\Windows\system32\wsl.exe' is not recognized as an internal or external command, operable program or batch file.

It turned out that I was running 32-bit vscode on 64-bit windows11, so the wsl path should be `C:\Windows\Sysnative\wsl.exe` instead of `C:\Windows\System32\wsl.exe`.
I've sovled this problem by reinstalling my vscode, but maybe someone else would encounter it again.

**Comment by ktunprasert** [comment]
Had this problem too. It turned out I didn't have a default distribution set since I had some docker stuff as well as Ubuntu. All I had to do was `wsl -l` to check the possible distros and then set the default distro to my Ubuntu-20.04 image `wsl -d Ubuntu-20.04`
![image](https://user-images.githubusercontent.com/35368006/174459280-06357b16-4e78-4d22-9be0-b6bac9ec089b.png)
