### ISSUE TITLE
"Toggle Vim Mode" setting (enable/disable extension)

### ISSUE THREAD

**Issue by azaslavsky** [vscode-neovim/vscode-neovim#794]
I'm not sure if this is possible given the architecture of this plugin (ie, defers to an external instance of neovim for actual implementation), but it would be nice to have a programmable `Toggle Vim Mode` hotkey, similar to what is currently available in the `vscodevim` extension.  There are a number of cases in which I would like to completely "disable" vim and go back to regular old VSCode editing, but this is not currently possible.

**Comment by trkoch** [comment]
If by toggling we define Vscode stays in insert mode, my wild guess would be that this should be feasible. You can already sort of emulate it by not forwarding `<esc>` to the extension, this way requiring `<ctrl+c>` to be pressed.

**Comment by bencodesall** [comment]
+1 to this feature request!

Wonder is something like this is feasible:

1. `<command+shift+P>` to bring up "command palette"
2. start typing `vim` or `toggle` and brings up `Toggle vscode-neovim` on off (with indicator on bottom status bar)

I believe this is how `vscodevim` does it. That would be sufficient.

P.S. Love that I can now use my `neovim` setup within VS Code. Thanks for the work.

**Comment by aquadesk** [comment]
> 



> If by toggling we define Vscode stays in insert mode, my wild guess would be that this should be feasible. You can already sort of emulate it by not forwarding `<esc>` to the extension, this way requiring `<ctrl+c>` to be pressed.

it maybe possible but in some situations, it leave insert mode and we should keep getting into it.
i.e. start editing different files or click on search results..

**Comment by Valleeh** [comment]
Hey, sometimes in pair programming the plugin hinders me, so this functionality would be great.
After waiting for about half a year, I decide to take my luck into my own hands. 
In my fork, it works. I added a switch to keep the insert mode even if Esc or Buffer(file)change happens.
I added a second switch that just makes insert mode persist when buffer change happens.
And I added a setting (which oddly can't be changed(which I think is a bug in the app programming) that switches to insert mode instead of VisualMode when text is selected with the mouse.
I guess it's not really PR ready yet, and there's no testing and so on. I wanted to ask if this functionality is wanted, and how it should be implemented, then i would take care for it if wanted. 
https://github.com/Valleeh/vscode-neovim
Best
Valentin Wunderlich

**Comment by justinmk** [comment]
@Valleeh  https://github.com/vscode-neovim/vscode-neovim/compare/master...Valleeh:vscode-neovim:neovimtoggle?expand=1 looks like a lot of code for this, but yes this issue is open because it's probably worthwhile.

**Comment by jonaprieto** [comment]
Is this the command "Neovim: turn on/off".

<img width="888" alt="image" src="https://github.com/vscode-neovim/vscode-neovim/assets/1428088/cec2323d-65a1-47ee-908c-f67303ff028b">

**Comment by justinmk** [comment]
Closed by https://github.com/vscode-neovim/vscode-neovim/pull/1033

**Comment by AaronBittel** [comment]
There are commands "Neovim: Stop Extension" and "Neovim: Restart Extension"
