### ISSUE TITLE
Cursor doesn't show correctly in python jupyter notebook at first

### ISSUE THREAD

**Issue by Civitasv** [vscode-neovim/vscode-neovim#846]
When entering in python jupyter notebook at first, the mode of vim is `normal` , but the cursor is not a **filled box**, but a **bar**.

**Fisrt Open, it's a bar:**

![image](https://user-images.githubusercontent.com/37768049/161234097-861833c2-4091-4a9b-a919-a1d49bd98933.png)

**After input **:**(didn't click ESC):**

![image](https://user-images.githubusercontent.com/37768049/161234546-6daa902a-9215-434d-8a79-2395eb5e1ec0.png)

**Then input w, it becomes a filled box:**

![image](https://user-images.githubusercontent.com/37768049/161234670-d1e340ef-2137-4196-8300-2a9dfb40ea0b.png)

It's not a big bug, but a little annoying.

**Comment by trkoch** [comment]
Confirmed. For me, cursor is show correctly (block) at first. But after switching to another tab, the cursor is displayed as bar. Workaround is to `a esc`. Interestingly the cursor in non-notebook tabs is not affected.

**Comment by trkoch** [comment]
Did some digging. The extension correctly sets the `block` cursor style for the notebook editor document [options](https://code.visualstudio.com/api/references/vscode-api#TextEditorOptions). This does not update the cursor style in the cell, possible due to a limitation or a bug in VSCode. A notebook editor contains notebook cells. The [notebook cells](https://code.visualstudio.com/api/references/vscode-api#NotebookCell) themselves do not allow its options to be changed.

**Comment by trkoch** [comment]
I created an upstream [issue](https://github.com/microsoft/vscode/issues/170156) which is now in community review. Please upvote!

**Comment by trkoch** [comment]
Workaround

`autocmd BufEnter *.ipynb#* if mode() == 'n' | call feedkeys("a^[")`

(You may need to type `C-V<esc>` instead of ^[)

**Comment by theol0403** [comment]
Can you explain why it seems to start working after a bit? I feel like it's not totally broken, or else it would never be a block. It just seems to randomly get stuck.

**Comment by trkoch** [comment]
> Can you explain why it seems to start working after a bit?

Good point. I have no explanation, only observations. As you already mentioned, setting the cursor style to block from via the VSCode API works as expected after the editor has been focused for a bit. Specifically after the (Vim) `BufEnter` event, perhaps earlier, but not later (because otherwise the workaround wouldn't help). My guess is this is some kind of async issue (style set before notebooks have been initialized), though not a race condition (it never works as expected). I know this is all very vague.



I'll continue testing my workaround. Maybe an (intermediate) option is to add it to our custom Vim scripts.

**Comment by datacubeR** [comment]
> autocmd BufEnter *.ipynb#* if mode() == 'n' | call feedkeys("a\<C-c>")

I can confirm your workaround works... thank you so much, this was being super annoying, so much that I was about to quit...
