### ISSUE TITLE
Cursor stuck after opening a large file with more than 1M lines.

### ISSUE THREAD

**Issue by futurehome** [vscode-neovim/vscode-neovim#85]
After opening a very large file, the cursor just stuck and can't move any more.

Thanks,
Alex

**Comment by scalavision** [comment]
I have kind of the same problem, but on any file size. It only occurs in first window (CTRL + 1), but all tabs in that window is affected. If I move to window 2+ everything works. Moving back, it gets stuck again. I am not able to re-enable it in any way. Closing / opening, reloading etc. still does not work.

**Comment by CodeChangingMe** [comment]
I have kind of the same problem~

**Comment by Dominux** [comment]
I've got a similar one problem: going in the second window toward the end of a file stops when the line number reaching number like 101, 201, 301, etc. After that any movements that can move you forward (<j>, <}>, <G>, `number of any of the next lines` + <gg>) don't work. Moreover, clicking the cursor to any place immediately returns you to the previous "stop point" (like, if you were somewhere between `101` and `201` - after click to any place you'll get to `101`).
I don't know why it behaves like it does... It seemed to be an ultimate decent editor experience because of it's involving VSCode features and Neovim's ones, and it works better and faster than "Vim" extension for VSCode that I'd used for several recent months, and it has no kinda bugs those are in the "Vim" extension (like bad macros serving, changing theme to default after using macros or saving a file, etc).
Yeah, sry, from describing an issue I went to describing my vision and opinion...

**Comment by docfantam** [comment]
> I've got a similar one problem: going toward the end of a file stops after reaching the line number like 101, 201, 301, etc. After that any movements that can move you forward (, <}>, , `number of any of the next lines` + ) don't work. Moreover, clicking the cursor to any place immediately returns you to the previous "stop point" (like, if you were somewhere between `101` and `201` - after click to any place you'll get to `101`).

Yes, this exactly!!! I was editing an HTML file today (~250 lines) and the cursor kept getting stuck at line 101. I first thought the issue was HTML specific and even disabled some extensions like Prettier and Image Preview. Only then I found it to happen with every file. Everything else is working just fine. But with this issue, it is sort of unusable for me atm unless I'm working with really small files (< 100 lines).

**Comment by omikun** [comment]
I'm seeing this issue from the latest neovim extension v0.0.82 and neovim 0.5.0. Cursor stuck at line 101 for all files with more than 101 lines and in all tab positions.

**Comment by anthonydwan** [comment]
I'm on neovim extension v0.083 and neovim 0.60 (using VSCode extension and Xubuntu) and I also get stuck at every 100 lines. If I press j/k/{/} long enough I could sometimes get out of it but it's impossible to work in that.

**Comment by asvetliakov** [comment]
@omikun @anthonydwan you have init.vim conflict. Remove init.vim and try again. Then try to find offending plugin/neovim setting. And this issue is about different problem
