### ISSUE TITLE
Inconsistent results when pressing o [normal mode]

### ISSUE THREAD

**Issue by Dandarprox** [vscode-neovim/vscode-neovim#864]
Sometimes when I press o the new line is created right after the current line, but for some reason the cursor jumps several lines at a time and it is not placed in the new line. I don't have anything in my current config remotely related with `o` nor my VSCode settings modify the cursor behavior. What can I do?

**Comment by zhuzhzh** [comment]
I hit the same issue.

**Comment by guyguy2001** [comment]
When you get this issue, does the rest of neovim work correctly?
I sometimes get into a corrupted state where it seems like neovim thinks it's editing different text from what actually is in vscode, and I may or may not have encountered this issue there (I'm not sure whether what I remember is this issue or not).
So I wonder if this problem is just a symptom of the other one, or if it happens on it's own.

Could you share footage of this if you encounter this issue again?

**Comment by xgrei** [comment]
I hit the same issue.

I try to disable all extensions except neovim, the problem still exists.

**Comment by xgrei** [comment]
https://user-images.githubusercontent.com/57981640/167289646-2c7010df-bce9-434f-9c68-26e2e44a3ed6.mp4

this is screen recording, only enabled neovim extension.

**Comment by theol0403** [comment]
This might be fixed by https://github.com/vscode-neovim/vscode-neovim/pull/992, can you give it a try?

**Comment by Jendker** [comment]
This issue occurs with neovim nightly but not v0.8.3. Just for the reference.
