### ISSUE TITLE
text is grayed out when starting insert mode behind a tab character

### ISSUE THREAD

**Issue by crinccc** [vscode-neovim/vscode-neovim#895]
This is very prominent when I use normal mode o or O as the newline will have been automatically indented. 1 work around I think will work is if I change my tab to use space instead. But I prefer the pure tab character.
![image](https://user-images.githubusercontent.com/86910893/167091701-ce606ec7-c6e4-4874-b533-0b338c40ff5d.png)

**Comment by justinmk** [comment]
works fine for me. insufficient steps provided.

**Comment by tbscode** [comment]
Experienced a similar issue with github-copilot plugin enabled.
It somehow seems to confuse which code to mark as suggestion if `vscode-neovim` plugin is enabled.
This is not that big of an issue to me since I have it disabled most of the time anyways, but a workaround in vscode is to change the highlight color for copilot:

```
"workbench.colorCustomizations": {
        "editorGhostText.border": "#ff0000",
        "editorGhostText.foreground": "#ff0000",
}
```

There is still somewhat of a visual glitch ( in regards to what is marked as suggestion ) but then you can clearly read the suggestions.

@justinmk maybe if this was you issue also you can add github copilot to the title.

**Comment by biiome** [comment]
I am having the same issue. I don't use Copilot or any AI suggestion tool. I changed the highlight colour but that had not effect. Anyone have a solution for this?
