### ISSUE TITLE
feature: get vscode "when" context from init.vim

### ISSUE THREAD

**Issue by gabrieldechichi** [vscode-neovim/vscode-neovim#986]
I'm looking for a way to express keybindings which are aware of VSCode state, in a `init.vim` or `init.lua` file (similar to `when` in `keybinding.json`).

For example, I'd like to be able to achieve this in `init.vim`:

```
    {
        "key": "space p",
        "command": "editor.action.showHover",
        "when": "editorTextFocus"
    },
    {
        "key": "space p",
        "command": "inserteditor.debug.action.showDebugHover",
        "when": "neovim.mode == normal && editorTextFocus && inDebugMode",
    }
```

As you can see, the same keybinding perform different commands depending on the editor's context.

**Comment by theol0403** [comment]
Related: #764

There would need to be things implemented for this to work:
- vscode -> init.vim communication. So that init.vim sends query to vscode, vscode replies, and then keybinding is conditionally evaluated
- conditional vim keybindings
- custom vscode command that reads context 

The first two seem very difficult, as neovim does not really work this way. Calling an async function whenever you type a key, to check if the binding should trigger would be slow and hard to implement.

Just use vscode's native, performant syntax for implementing this.

**Comment by BIKA-C** [comment]
Instead of a conditional keymap, we just need to query the context key in vscode and wrap the mapping in a function with `if` `<RHS>` `else` return.  I saw there is a public unofficial api for querying the context keys: [link](https://stackoverflow.com/questions/43372232/a-method-to-expose-the-vscode-active-when-clause-contexts)

> There is a non public api for getting the when context in effect. You can use getValue(key: string). It is available from the work on this issue ticket:
>
> [Lift setContext from a command to proper API Microsoft/vscode#10471](https://github.com/Microsoft/vscode/issues/10471)
>
>and the source can be viewed here:
>
> [contextKeyService.ts](https://github.com/microsoft/vscode/blob/b5a1bb34e9c6b77c2a8ccf54bcdbb4bac4d420cb/src/vs/platform/contextkey/browser/contextKeyService.ts#L57)
>
>by using getValue(key: string)
>
>It is still work in progress as of May 2017. Thank you. Good day.

**Comment by theol0403** [comment]
Thanks for the info. Still don't know how we'd run an extension request from nvim and then wait for a reply

**Comment by ghry5** [comment]
Is this now possible with the new lua api? Seems like something like `require("vscode-neovim").get_config(...)` should be fairly similar in requirements.

**Comment by xiyaowong** [comment]
Impossible, 'when' is based on dom
